import { Platform, StyleSheet } from 'react-native';
import { AppColors, BorderRadius, FontSizes, Spacing } from '../constants/theme';

export const COLORS = AppColors;
export const FONTS = { family: 'System' };

export const styles = StyleSheet.create({
  container: { flex: 1 },
  map: { flex: 1 },
  detailModalContainer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 2000 },
  detailModalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' },
  detailModalCard: { borderRadius: BorderRadius.xl, maxHeight: '80%', paddingBottom: Spacing.xl, paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg, overflow: 'hidden', backgroundColor: Platform.select({ ios: 'rgba(20, 20, 25, 0.75)', android: 'rgba(20, 20, 25, 0.8)', default: 'rgba(20, 20, 25, 0.75)' }), borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.15)', shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.25, shadowRadius: 20, elevation: 10 },
  scrollView: { flex: 1 },
  stickyHeader: { 
    backgroundColor: 'transparent', 
    borderBottomWidth: 0, 
    borderBottomColor: 'transparent',
    // Extend background to card edges
    marginHorizontal: -Spacing.xl,
    paddingHorizontal: Spacing.xl,
    // Provide top padding without negative margins to avoid layout issues
    paddingTop: Spacing.lg,
  },
  stickyHeaderStuck: {
    backgroundColor: COLORS.background.primary,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border.primary,
  },
  titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md },
  title: { fontSize: FontSizes.title, fontWeight: 'bold', fontFamily: FONTS.family, color: COLORS.primary },
  titleCollapsed: { marginBottom: Spacing.sm },
  refreshButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 20,
    padding: 4,
    width: 40,
    height: 40,
    backgroundColor: 'transparent',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  refreshIconSpinning: { opacity: 0.5 },
  subtitle: { fontSize: FontSizes.flightDate, fontFamily: FONTS.family, color: COLORS.secondary, marginTop: -Spacing.sm, marginBottom: Spacing.md },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.background.secondary, borderRadius: BorderRadius.md, paddingHorizontal: Spacing.md, marginBottom: Spacing.xl, borderWidth: 1, borderColor: COLORS.border.secondary },
  searchContainerCollapsed: { marginBottom: Spacing.md, paddingHorizontal: Spacing.sm },
  searchInput: { flex: 1, paddingVertical: Spacing.md, paddingHorizontal: Spacing.sm, color: COLORS.primary, fontSize: FontSizes.searchLabel, fontFamily: FONTS.family },
  frequentlyUsedSection: { marginBottom: Spacing.lg },
  sectionLabel: { fontSize: FontSizes.timeLabel, fontFamily: FONTS.family, color: COLORS.secondary, letterSpacing: 0.5, marginBottom: Spacing.md, fontWeight: '600' },
  frequentlyUsedItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.background.primary, borderRadius: BorderRadius.md, padding: Spacing.md, marginBottom: Spacing.sm, borderWidth: 1, borderColor: COLORS.border.primary },
  searchButtonText: { flex: 1, paddingVertical: Spacing.md, paddingHorizontal: Spacing.sm, color: COLORS.secondary, fontSize: FontSizes.searchLabel, fontFamily: FONTS.family },
  frequentlyUsedIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: COLORS.background.secondary, alignItems: 'center', justifyContent: 'center', marginRight: Spacing.md },
  frequentlyUsedText: { flex: 1 },
  frequentlyUsedName: { fontSize: FontSizes.searchLabel, fontFamily: FONTS.family, color: COLORS.primary, fontWeight: '600', marginBottom: 2 },
  frequentlyUsedSubtitle: { fontSize: FontSizes.daysLabel, fontFamily: FONTS.family, color: COLORS.secondary },
  noTrainsContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: Spacing.xl, gap: Spacing.md },
  noTrainsText: { fontSize: FontSizes.flightDate, fontFamily: FONTS.family, color: COLORS.secondary },
  flightCard: { flexDirection: 'row', backgroundColor: COLORS.background.primary, borderRadius: BorderRadius.md, padding: Spacing.lg, marginBottom: Spacing.md, borderWidth: 1, borderColor: COLORS.border.primary },
  flightLeft: { alignItems: 'center', justifyContent: 'center', marginRight: Spacing.lg, minWidth: 60 },
  daysAway: { fontSize: FontSizes.daysAway, fontWeight: 'bold', fontFamily: FONTS.family, color: COLORS.primary, lineHeight: 36 },
  daysLabel: { fontSize: FontSizes.daysLabel, fontFamily: FONTS.family, color: COLORS.secondary, marginTop: Spacing.xs, letterSpacing: 0.5 },
  flightCenter: { flex: 1 },
  flightHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: Spacing.xs },
  amtrakLogo: { width: 16, height: 16, marginRight: 3, resizeMode: 'contain' },
  flightNumber: { fontSize: FontSizes.flightNumber, fontFamily: FONTS.family, color: COLORS.primary, fontWeight: '600', marginLeft: 3, marginRight: Spacing.md },
  flightDate: { fontSize: FontSizes.flightDate, fontFamily: FONTS.family, color: COLORS.secondary, marginLeft: 'auto' },
  route: { fontSize: FontSizes.route, fontWeight: '600', fontFamily: FONTS.family, color: COLORS.primary, marginBottom: Spacing.sm },
  timeRow: { flexDirection: 'row', justifyContent: 'space-between' },
  timeInfo: { flexDirection: 'row', alignItems: 'center' },
  arrowIcon: { width: 14, height: 14, borderRadius: 7, alignItems: 'center', justifyContent: 'center', marginRight: Spacing.sm },
  departureIcon: { backgroundColor: COLORS.tertiary },
  arrivalIcon: { backgroundColor: COLORS.tertiary },
  timeCode: { fontSize: FontSizes.timeCode, fontFamily: FONTS.family, color: COLORS.secondary, marginRight: Spacing.sm },
  timeValue: { fontSize: FontSizes.timeValue, fontFamily: FONTS.family, color: COLORS.primary, fontWeight: '500' },
  liveTrainMarker: { backgroundColor: '#10B981', borderRadius: 16, width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: 'white', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 4, elevation: 5 },
  realtimeBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, marginLeft: 8 },
  onTimeBadge: { backgroundColor: '#10B981' },
  delayedBadge: { backgroundColor: '#EF4444' },
  realtimeBadgeText: { color: 'white', fontSize: 10, fontWeight: '600' },
  progressContainer: { backgroundColor: COLORS.background.secondary, borderRadius: BorderRadius.md, padding: Spacing.md, marginBottom: Spacing.md, borderWidth: 1, borderColor: COLORS.border.secondary },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.xs },
  progressLabel: { fontSize: FontSizes.searchLabel, fontFamily: FONTS.family, color: COLORS.primary, fontWeight: '600' },
  progressValue: { fontSize: FontSizes.searchLabel, fontFamily: FONTS.family, color: COLORS.secondary },
  progressTrack: { height: 8, backgroundColor: COLORS.border.secondary, borderRadius: 999, overflow: 'hidden', marginBottom: Spacing.xs },
  progressBar: { height: '100%', backgroundColor: COLORS.accentBlue, borderRadius: 999 },
  progressStep: { fontSize: FontSizes.daysLabel, fontFamily: FONTS.family, color: COLORS.secondary },
});